replicaCount: 1

containers:
  - name: nginx-container
    image: nginx
    tag: latest
    imagePullPolicy: Always
    port: 80
    protocol: TCP
    mountPath: /data
    enableConfigMap: true
    configMapData:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    enableSecret: true
    secretData:
      POSTGRES_USER: cG9zdGdyZXM=
      POSTGRES_PASSWORD: cG9zdGdyZXM=
      POSTGRES_HOST_AUTH_METHOD: dHJ1c3Q=

  - name: postgres-container
    image: postgres
    tag: 9.4
    imagePullPolicy: IfNotPresent
    port: 5432
    protocol: TCP
    mountPath: /data
    enableConfigMap: true
    configMapData:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    enableSecret: true
    secretData:
      MY_USERNAME: bmVvNGo=  # Base64-encoded value: "neo4j"
      MY_PASSWORD: cGFzc3dvcmQ=  # Base64-encoded value: "password"

createPVC: false
pvc:
  storageClassName: do-block-storage
  accessMode: ReadWriteOnce
  storageSize: 5Gi

createService: false
serviceType: ClusterIP
resources: {}
  # limits:
  #   cpu: 500m
  #   memory: 1Gi
  # requests:
  #   cpu: 200m
  #   memory: 500Mi
imagePullSecrets: []
  # - name: my-image-pull-secret
enableIngress: true
virtualServiceHost: some.exemplo.com
virtualServicePrefix: /

