{{- $releaseName := .Release.Name -}}
{{- range $index, $container := .Values.containers }}
{{- if and $container.enableConfigMap (or (eq $index 0) (gt (len $.Values.containers) 1)) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ if eq (len $.Values.containers) 1 }}{{ $releaseName }}-configmap{{ else }}{{ $releaseName }}-{{ $container.name }}-configmap{{ end }}
data:
{{- range $key, $value := $container.configMapData }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
{{- end }}
