apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: 
spec:
  gateways:
  - some-gateway
  hosts:
  - some.exemplo.com
  http:
  - headers:
      request:
        set:
          X-Forwarded-Proto: https
    match:
    - uri:
        prefix: /
    name: some-route
    route:
    - destination:
        host: some-service
        port:
          number: 80
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: some-gateway
spec:
  selector:
    istio: ingress
  servers:
  - hosts:
    - some.exemplo.com
    port:
      name: http
      number: 443
      protocol: HTTP
