{{- if .Values.enableIngress }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Release.Name }}-gateway
spec:
  selector:
    istio: ingress
  servers:
  - hosts:
    - {{ .Values.virtualServiceHost }}
    port:
      name: http
      number: 443
      protocol: HTTP
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-virtualservice
spec:
  gateways:
  - {{ .Release.Name }}-gateway
  hosts:
  - {{ .Values.virtualServiceHost }}
  http:
  - headers:
      request:
        set:
          X-Forwarded-Proto: https
    match:
    - uri:
        prefix: /
    name: some-route
    route:
    - destination:
        host: {{ .Values.serviceName }}
        port:
          number: {{ .Values.servicePort }}
{{- end }}
