{{- range $container := .Values.containers }}
{{- if $container.enableSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-{{ $container.name }}-secret
type: {{ $container.secretType | default "Opaque" }}
data:
{{- range $key, $value := $container.secretData }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
