{{- $releaseName := .Release.Name -}}
{{- range $index, $container := .Values.containers }}
{{- if and $container.enableSecret (or (eq $index 0) (gt (len $.Values.containers) 1)) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ if eq (len $.Values.containers) 1 }}{{ $releaseName }}-secret{{ else }}{{ $releaseName }}-{{ $container.name }}-secret{{ end }}
type: Opaque
data:
{{- range $key, $value := $container.secretData }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
