{{- range $container := .Values.containers }}
{{- if $container.enableSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-{{ $container.name }}-secret
type: Opaque
data:
{{- range $key, $value := $container.secretData }}
  {{ $key }}: {{ $value | quote | b64enc }}
{{- end }}
{{- end }}
{{- end }}
